apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod1
      labels:
        app: nginx
    spec:
     containers:
     - name: nginx-container
       image: nginx:alpine
       ports:
       - containerPort: 80
